# Generated by Django 4.1.7 on 2023-07-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_invoice_client_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
