# Generated by Django 4.1.7 on 2023-07-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='productininvoice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
